### ISSUE TITLE
adding fields

### ISSUE THREAD

**Issue by running2bwell** [zachjohnston/r2bw-alpha#57]
Please add fields for street, city, State, zip and shoe size
Also we need to keep track of when people pay their annual dues. Probably just a date paid and then I can sort in Excel

**Comment by ShepherdBook** [comment]
Created #58 for the dues paid field, since it should only be editable by admins

**Comment by ShepherdBook** [comment]
w6-w12
m7-m15

**Comment by ShepherdBook** [comment]
@running2bwell This is deployed
